apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bj82xxv8o-dotnet-basic
  janus-idp.io/tekton: bj82xxv8o-dotnet-basic
  backstage.io/kubernetes-id: bj82xxv8o-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bj82xxv8o-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
